# Generated by Django 6.0.2 on 2026-02-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14)),
                ('estado_nascimento', models.CharField(max_length=2)),
                ('cidade_nascimento', models.CharField(max_length=100)),
                ('area_atuacao', models.CharField(max_length=100)),
                ('crm', models.CharField(blank=True, max_length=20, null=True)),
                ('contato', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
